# Generated by Django 3.0.3 on 2020-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
    ]
